Update .github/workflows/pr_action.yml

diff --git a/.github/workflows/pr_action.yml b/.github/workflows/pr_action.yml
--- a/.github/workflows/pr_action.yml
+++ b/.github/workflows/pr_action.yml
@@ -28,7 +28,6 @@ jobs:
           repository: ONLYOFFICE/office-js-api-declarations
           token: ${{ secrets.READ_PAT }}
           ref: master
-          fetch-depth: 0
           path: office-js-api-declarations
 
       - name: Checkout repository with examples office-js-api
@@ -37,7 +36,6 @@ jobs:
           repository: ONLYOFFICE/office-js-api
           token: ${{ secrets.READ_PAT }}
           ref: master
-          fetch-depth: 0
           path: office-js-api
 
       - name: Checkout sdkjs repository
@@ -54,12 +52,18 @@ jobs:
           repository: ONLYOFFICE/sdkjs-forms
           token: ${{ secrets.READ_PAT }}
           ref: master
-          fetch-depth: 0
           path: sdkjs-forms
-      
-      - name: Set env
+
+      - name: Fetch all repos without tags
         run: |
           git -C build_tools fetch --no-tags || echo "Failed to fetch in build_tools"
+          git -C office-js-api-declarations fetch --no-tags || echo "Failed to fetch in office-js-api-declarations"
+          git -C office-js-api fetch --no-tags || echo "Failed to fetch in office-js-api"
+          git -C sdkjs fetch --no-tags || echo "Failed to fetch in sdkjs"
+          git -C sdkjs-forms fetch --no-tags || echo "Failed to fetch in sdkjs-forms"
+
+      - name: Set env
+        run: |
           branches=$(git -C build_tools branch -r | grep -E 'origin/(release/v|hotfix/v)' | sed 's|origin/||; s/^ *//; s/ *$//' | paste -sd "," -)
           echo "branches=$branches" >> $GITHUB_ENV
           echo "$branches"
