Update .github/workflows/pr_action.yml

diff --git a/.github/workflows/pr_action.yml b/.github/workflows/pr_action.yml
--- a/.github/workflows/pr_action.yml
+++ b/.github/workflows/pr_action.yml
@@ -30,34 +30,14 @@ jobs:
         with:
           repository: ONLYOFFICE/office-js-api-declarations
           token: ${{ secrets.READ_PAT }}
-          ref: master
+          ref: develop
           path: office-js-api-declarations
 
-      - name: Checkout repository with examples office-js-api
-        uses: actions/checkout@v4
-        with:
-          repository: ONLYOFFICE/office-js-api
-          token: ${{ secrets.READ_PAT }}
-          ref: master
-          path: office-js-api
-
-      - name: Checkout sdkjs-forms repository
-        uses: actions/checkout@v4
-        with:
-          repository: ONLYOFFICE/sdkjs-forms
-          token: ${{ secrets.READ_PAT }}
-          ref: master
-          path: sdkjs-forms
-
-      - name: Fetch all repos without tags
+      - name: Fetch build_tools without tags
         run: |
           git -C build_tools fetch --no-tags || echo "Failed to fetch in build_tools"
-          #git -C office-js-api-declarations fetch --no-tags || echo "Failed to fetch in office-js-api-declarations"
-          #git -C office-js-api fetch --no-tags || echo "Failed to fetch in office-js-api"
-          #git -C sdkjs fetch --no-tags || echo "Failed to fetch in sdkjs"
-          #git -C sdkjs-forms fetch --no-tags || echo "Failed to fetch in sdkjs-forms"
 
-      - name: Set env
+      - name: Check release/hotfix branch for build
         run: |
           branches=$(git -C build_tools branch -r | grep -E 'origin/(release/v|hotfix/v)' | awk '{sub("origin/", ""); print}')
           echo "List of release/hotfix branches: $branches"
@@ -67,6 +47,14 @@ jobs:
           echo "Branch for build: $max_branch"
           echo "build_branch=$max_branch" >> $GITHUB_ENV
 
+      - name: Checkout repository with examples office-js-api
+        uses: actions/checkout@v4
+        with:
+          repository: ONLYOFFICE/office-js-api
+          token: ${{ secrets.READ_PAT }}
+          ref: master
+          path: office-js-api
+
       - name: Checkout sdkjs repository
         uses: actions/checkout@v4
         with:
@@ -75,6 +63,14 @@ jobs:
           ref: ${{ env.build_branch }}
           path: sdkjs
 
+      - name: Checkout sdkjs-forms repository
+        uses: actions/checkout@v4
+        with:
+          repository: ONLYOFFICE/sdkjs-forms
+          token: ${{ secrets.READ_PAT }}
+          ref: ${{ env.build_branch }}
+          path: sdkjs-forms
+
       - name: Set up Git
         run: |
           git config --global user.name "github-actions[bot]"
@@ -82,39 +78,17 @@ jobs:
 
       - name: Generate docs for each branch
         run: |
-          echo "-------------------------------------------"
-          git -C build_tools switch "$max_branch" || echo "Failed to switch $max_branch in build_tools"
-          echo "$max_branch"
-          echo "-------------------------------------------"
+          git -C build_tools switch "$branch" || echo "Failed to switch $branch in build_tools"
+          cd build_tools/scripts/sdkjs_common/jsdoc
+          npm install
+          python generate_docs_json.py
+          python generate_docs_plugins_json.py
+          cd ../../../../office-js-api-declarations
 
-          for branch in $(echo "$branches" | tr ',' '\n'); do
-            echo "-------------------------------------------"
-            echo "Branch: $branch"
-            git -C build_tools switch "$branch" || echo "Failed to switch $branch in build_tools"
-            if [ ! -d "build_tools/scripts/sdkjs_common/jsdoc" ]; then
-              echo "Directory for build does not exist. Skipping $branch branch."
-              continue
-            fi
-            
-            git -C office-js-api-declarations reset --hard HEAD || echo "Failed to reset in office-js-api-declarations"
-            git -C office-js-api-declarations switch "master" || echo "Failed to switch master in office-js-api-declarations"
-            git -C office-js-api-declarations switch "$branch" || git -C office-js-api-declarations switch -c "$branch" || echo "Failed to create $branch in office-js-api-declarations"
-
-            git -C office-js-api switch "$branch" || echo "Failed to switch $branch in office-js-api"
-            git -C sdkjs switch "$branch" || echo "Failed to switch $branch in sdkjs"
-            git -C sdkjs-forms switch "$branch" || echo "Failed to switch $branch in sdkjs-forms"
-
-            cd build_tools/scripts/sdkjs_common/jsdoc
-            npm install
-            python generate_docs_json.py
-            python generate_docs_plugins_json.py
-            cd ../../../../
-
-            if ! git -C office-js-api-declarations diff --exit-code; then
-              git -C office-js-api-declarations add .
-              git -C office-js-api-declarations commit -m "Add documentation update from GitHub Actions"
-              git -C office-js-api-declarations push origin $branch
-            else
-              echo "Nothing to commit in $branch in office-js-api-declarations"
-            fi
-          done
+          if ! git diff --exit-code; then
+            git add .
+            git commit -m "Add documentation update from GitHub Actions"
+            git push origin $branch
+          else
+            echo "Nothing to commit"
+          fi
