Update .github/workflows/pr_action.yml

diff --git a/.github/workflows/pr_action.yml b/.github/workflows/pr_action.yml
--- a/.github/workflows/pr_action.yml
+++ b/.github/workflows/pr_action.yml
@@ -59,7 +59,7 @@ jobs:
       
       - name: Set env
         run: |
-          git -C build_tools fetch || echo "Failed to fetch in build_tools"
+          git -C build_tools fetch --no-tags || echo "Failed to fetch in build_tools"
           branches=$(git -C build_tools branch -r | grep -E 'origin/(release/v|hotfix/v)' | sed 's|origin/||; s/^ *//; s/ *$//' | paste -sd "," -)
           echo "branches=$branches" >> $GITHUB_ENV
           echo "$branches"
